// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PaymentReviewRequestStatus.
const (
	PaymentReviewRequestStatusApproved PaymentReviewRequestStatus = "approved"
	PaymentReviewRequestStatusRejected PaymentReviewRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PaymentReviewRequestStatus enum.
func (e PaymentReviewRequestStatus) Valid() bool {
	switch e {
	case PaymentReviewRequestStatusApproved:
		return true
	case PaymentReviewRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PaymentReviewResponseStatus.
const (
	PaymentReviewResponseStatusApproved PaymentReviewResponseStatus = "approved"
	PaymentReviewResponseStatusRejected PaymentReviewResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PaymentReviewResponseStatus enum.
func (e PaymentReviewResponseStatus) Valid() bool {
	switch e {
	case PaymentReviewResponseStatusApproved:
		return true
	case PaymentReviewResponseStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus.
const (
	PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatusApproved PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus = "approved"
	PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatusRejected PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus enum.
func (e PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatusApproved:
		return true
	case PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatusRejected:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Example: 401
	Code int `json:"code"`

	// Message Example: Unauthenticated: missing or invalid token
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	// Amount Example: 100.00
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Example: 1
	Id *string `json:"id,omitempty"`

	// Merchant Example: Merchant A
	Merchant *string `json:"merchant,omitempty"`

	// Status Example: completed , processing , or failed
	Status *string `json:"status,omitempty"`
}

// PaymentReviewRequest defines model for PaymentReviewRequest.
type PaymentReviewRequest struct {
	// Status Example: approved
	Status *PaymentReviewRequestStatus `json:"status,omitempty"`
}

// PaymentReviewRequestStatus Example: approved
type PaymentReviewRequestStatus string

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// PaymentId defines model for payment_id.
type PaymentId = string

// Sort Example: -created_at
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	// Limit Example: 10
	Limit *int `json:"limit,omitempty"`

	// Page Example: 1
	Page     *int       `json:"page,omitempty"`
	Payments *[]Payment `json:"payments,omitempty"`

	// Total Example: 42
	Total *int `json:"total,omitempty"`
}

// PaymentReviewResponse defines model for PaymentReviewResponse.
type PaymentReviewResponse struct {
	// Message Example: Payment review summary
	Message *string `json:"message,omitempty"`

	// Status Example: approved
	Status *PaymentReviewResponseStatus `json:"status,omitempty"`
}

// PaymentReviewResponseStatus Example: approved
type PaymentReviewResponseStatus string

// PaymentSummaryResponse defines model for PaymentSummaryResponse.
type PaymentSummaryResponse struct {
	// Failed Example: 20
	Failed *int `json:"failed,omitempty"`

	// Processing Example: 10
	Processing *int `json:"processing,omitempty"`

	// Success Example: 70
	Success *int `json:"success,omitempty"`

	// Total Example: 100
	Total *int `json:"total,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Search search payments by merchant name or payment id
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// DateFrom filter payments created on or after this date (YYYY-MM-DD)
	DateFrom *openapi_types.Date `form:"date_from,omitempty" json:"date_from,omitempty"`

	// DateTo filter payments created on or before this date (YYYY-MM-DD)
	DateTo *openapi_types.Date `form:"date_to,omitempty" json:"date_to,omitempty"`

	// Page page number (1-indexed)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus defines parameters for PatchDashboardV1PaymentsPaymentIdReview.
type PatchDashboardV1PaymentsPaymentIdReview200JSONResponseBodyStatus string

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// PatchDashboardV1PaymentsPaymentIdReviewJSONRequestBody defines body for PatchDashboardV1PaymentsPaymentIdReview for application/json ContentType.
type PatchDashboardV1PaymentsPaymentIdReviewJSONRequestBody = PaymentReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostDashboardV1AuthLogin Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// GetDashboardV1Payments List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
	// GetDashboardV1PaymentsSummary Get payment summary
	// (GET /dashboard/v1/payments/summary)
	GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request)
	// PatchDashboardV1PaymentsPaymentIdReview Update payment review status
	// (PATCH /dashboard/v1/payments/{payment_id}/review)
	PatchDashboardV1PaymentsPaymentIdReview(w http.ResponseWriter, r *http.Request, paymentId PaymentId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// PostDashboardV1AuthLogin Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDashboardV1Payments List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDashboardV1PaymentsSummary Get payment summary
// (GET /dashboard/v1/payments/summary)
func (_ Unimplemented) GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PatchDashboardV1PaymentsPaymentIdReview Update payment review status
// (PATCH /dashboard/v1/payments/{payment_id}/review)
func (_ Unimplemented) PatchDashboardV1PaymentsPaymentIdReview(w http.ResponseWriter, r *http.Request, paymentId PaymentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "date_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_from", r.URL.Query(), &params.DateFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date_from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "date_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_to", r.URL.Query(), &params.DateTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date_to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date_to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1PaymentsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1PaymentsSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1PaymentsSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchDashboardV1PaymentsPaymentIdReview operation middleware
func (siw *ServerInterfaceWrapper) PatchDashboardV1PaymentsPaymentIdReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "payment_id" -------------
	var paymentId PaymentId

	err = runtime.BindStyledParameterWithOptions("simple", "payment_id", chi.URLParam(r, "payment_id"), &paymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "payment_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchDashboardV1PaymentsPaymentIdReview(w, r, paymentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/dashboard/v1/payments/{payment_id}/review", wrapper.PatchDashboardV1PaymentsPaymentIdReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments/summary", wrapper.GetDashboardV1PaymentsSummary)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFhdTxw3F/4rlt/3gqSzO7NJpEYj9SItbUQVVJQ0rRCgYGbOsE7G9sT2AFu0/7069nzueGGBNFew9rGf",
	"cx6fz7mlmRKVkiCtoektrZhmAizo5tdKgLSfeI6/cjCZ5pXlStKUHvk9crBPI8pxpWJ2SSMqmQD3qzsb",
	"UQ1fa64hp6nVNUTUZEsQDC+1qwqljdVcXtL1OqJGaTuF+0UJwWYGUEELOUEpUnAoczMnuKkkqZi1oKVJ",
	"yfks04Byn5g9J3uVhoLfkPPZOfmJ4L3PyDkTqpa4KRUZ7TOTPTuVrVFfa9Cr3iqn3FB/uGGiKnFrAEmj",
	"iV1rJMFUShpw1L5Tl1y+b1ZwIVPSgnSWs6oqecbQ8vizQfNvB4j/11DQlP4v7l8u9rsm/mhAe7Axexps",
	"rSWx6gtIwmROagOacFkoLRwOXUfti77jxj5KsUqrCrTl3sCSC25HDC2SjhYuLVyiqhGt2CWMxcJSTjd3",
	"M7cgzH1MNMbg2eY2pjVbud/KsnIE+erFFLM/qC4+Q2ZDtLYxgJQNGHwPVxyuvwGHAozZpKcD1Q6FmFoI",
	"5lx0w+UiaiyztbsIZC1oeoLgWl2BD0m0CnJ6Fg0uHwhMI3NnPjwB5EOjWs9Ms/INqCkYLyEfMfMi7F9a",
	"ZWAM2nC/M5o6Q+GR5I9ByakTLZLkaV40oOujZLVdKs3/gfxXrZXegalGEad87c6DtCjkaWr9JKWH3NFB",
	"FGaAK1by3CcGGtErVtbNq+QYF8ki6p2w0aq7NSVi203Oyt1SljcvQMubHosrSfyDI1SLmmnIUYCVhvZ4",
	"zv6Os7HTeKuGgZ8Es00w7na3PhQ7fQU88Wr0KGcTH+niZWqCL1tjzRZJMk+SUAYYlCSMGZftaUpzZmFm",
	"uYDQGZ5v3B4SEqCzJdtU5LBZJW/uSUfdCXSIErCgR6SPVBIhqU2I75CJJpn3aw0mQN5/nBAj6urvBBYE",
	"42Wg2YmoViUEN7wjBfujzXwSUQNZrbldfcAA8JAXwDRoDKH+12/t8//+959tD4M3+d3ewKW1lQ9IbBCc",
	"Etw6MvZrzZk8Yiuyz8zyQjGdkzdHB5g4QBsftot5Mk/QBFWBZBWnKX05T+YvaeQaRKddnLfH46tFjGEV",
	"l9gPOeqUfzkk0EX+QY45UhnbYf61QMNcB9X0lmDszypfPaGebH+jihlzrXQefo1hXPs7BifOgtl/3Axv",
	"NoYvkmRbyuzk4nH3uI7oq2Rx/6lpVXHe0xUGdyu55nZJnCnkB9KZgpLjZxu2ZJcQeLO3MHyyo1Y8Gg0Z",
	"J2Gle5HYtdzraHMg8LFMVEEaRcje/cnk2ba23ieGOweTiQLAdLZs0Q25WJE2KxK8FlFb1dwQFAR2lzwM",
	"uOClBd0DN0meKImQrMBNu+SGYJone8fHx8ezw8PZ/v4261HuU6GVGOkxqhah9PcwvS6gUBoeoZhVT1ML",
	"Bwwia3EBmuwtZlzmcLPdE9w4MsTLoWB1ad1cIrjkAgvHItTpbQI3mKogbmIhlSPHXR9C9gNTGDqJqGA3",
	"DTb2mXdqcvaYlBKa/p6YWJqy5IJ8WJBOzlDFQd7hxg4C2dyRbOLu1IOSzoduSHo0MZujy3fi5i3YLou0",
	"q3fQc9t/dlnHfkL0H3Jstpx+VPlYuUisNiZKn1n3YH45j8hp0xidUozi07YhOqUYQRtFGlEC7Dd/D3Lf",
	"nj24Agw+JXnfflzB3+Fzwbh/DAwlf7h/WEkGy4RL8vyQ6S+5upbP6Tcp8OEvCd/J5+5yi2a0A33VPl6t",
	"y6ZpTOO4VBkrl8rY9HXyOqHrs/W/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
