/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_API_BASE_URL: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

interface Window {
  /** Runtime-injected API base URL (see public/config.js, generated by build/docker/entrypoint.sh in production). */
  __API_BASE_URL__?: string
}
